### ISSUE TITLE
customized tags set

### ISSUE THREAD

**Issue by Weipengchen1** [leroy102/REVIVE#10]
Thanks for your wonderful job! I am wondering how you build the customized tags set? Could you give me some details about this?

**Comment by yuanze-lin** [comment]
Sorry for the late reply, I've been busy with some ongoing projects, you can obtain the tag set with the [Public Azure Tagging Service API](https://westus.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-2/operations/56f91f2e778daf14a499f21b).
