### ISSUE TITLE
请问文章中的tags是怎么得到的，大神求解答，感谢！！！

### ISSUE THREAD

**Issue by cmcv2022** [leroy102/REVIVE#12]
To construct the general domain tag set T¯, we collect the most frequently searched 400K queries in Bing Search as the tags.  
请问有相关的tags集合么？
如果是通过微软api获得，那么此处该如何理解呢

**Comment by yuanze-lin** [comment]
您好！感谢你对这篇工作的关注～

> 请问有相关的tags集合么？

这个目前没有，因为使用微软的数据，所以tag数据无法release.

> 如果是通过微软api获得，那么此处该如何理解呢

很抱歉给您带来误解，文章里面用的tag是基于微软的数据，但是如果你想要自己创建一个tag set，你可以使用一个公开的大数据集，然后使用微软api去得到这些tags，最后可以再筛选一些比较经常用到的tags作为tag set来检索.

希望能解决你的问题 : )

**Comment by cmcv2022** [comment]
谢谢
