### ISSUE TITLE
How should I identify the visual regions the model focuses on when predicting the answer?

### ISSUE THREAD

**Issue by white-day** [leroy102/REVIVE#14]
I noticed that the code uses the T5 model, and during answer prediction, all visual and language features are concatenated for prediction. How can I identify the important visual regions, as described in the 'Visualizing Results' section of the paper?

**Comment by yuanze-lin** [comment]
Thank you for your insightful question. I recommend referring to the paper for a more detailed explanation. In the 'Visualizing Results' section, the object regions represent the detected areas that are utilized to retrieve explicit knowledge.

**Comment by white-day** [comment]
I'm sorry, I may have expressed myself incorrectly. What I meant was how can I identify the important visual regions from the input in the code? In other words, I want to reproduce the 'Visualizing Results' section from the paper. How should I do that? Thank you for your explanation.
