### ISSUE TITLE
Problem when training model

### ISSUE THREAD

**Issue by ningkekeke** [leroy102/REVIVE#5]
Dear author, first its really appreciated about your work. When I am preparing to train the model, I get the following error, can you help me with it please. I've followed the former instructions already.
![image](https://user-images.githubusercontent.com/61769804/225841266-05f79380-37ae-44d7-acba-8e2146348ce8.png)

**Comment by yuanze-lin** [comment]
@ningkekeke what are your cuda and cudnn versions? I think they may be outdated.

**Comment by ningkekeke** [comment]
Thank your for your timely response, before asking the question, my cuda version was 10.3, then I updated to 11.3 and cudnn is 8.2, then I got the following error.
![image](https://user-images.githubusercontent.com/61769804/225870113-2333c8b6-2e96-49c3-b1c3-3122f1c85e99.png)
![image](https://user-images.githubusercontent.com/61769804/225869493-88eb6339-0727-4638-8441-21ef21904147.png)
![image](https://user-images.githubusercontent.com/61769804/225869585-5cbd0674-e3f4-436b-bf66-7935d78564bd.png)
Wish you all the best!

**Comment by yzleroy** [comment]
@ningkekeke have you install pytorch package according to requirements.txt, the cuda and cudnn versions of  pytorch package in requirements.txt should be 10.2 and 7605, maybe you need check it again

**Comment by yuanze-lin** [comment]
@ningkekeke Have you installed pytorch package according to requirements.txt? The cuda and cudnn versions of pytorch package in requirements.txt should be 10.2 and 7605, maybe you need check it again.

**Comment by yuanze-lin** [comment]
@ningkekeke Since there're no new responses, I close the issue, and if you have any more questions, you can reopen the issue.

**Comment by ningkekeke** [comment]
Thank you very much for your prompt reply and help, for some reasons I have not been able to work in the past few days, I am very sorry for not being able to reply to you in time, I reconfigured the environment according to your readme file, and then executed the command, but the error on the picture still appears. 
![image](https://user-images.githubusercontent.com/61769804/227195485-8637cf89-1218-4c98-8c67-251e5e197d53.png)
![image](https://user-images.githubusercontent.com/61769804/227194209-1e46b444-dd27-4ba2-aa9d-4b911aeb02ac.png)
![image](https://user-images.githubusercontent.com/61769804/227195143-f954bcf6-5064-4734-9bc8-0d17e9937f23.png)

**Comment by yuanze-lin** [comment]
@ningkekeke I've recently tested the codes in two different servers, and they all work.

**Comment by ningkekeke** [comment]
@yzleroy Ok, thank you very much for your work and help, I'll check my work again. Wish you good luck in your work!

**Comment by yuanze-lin** [comment]
@ningkekeke Hi, ningkekeke, you can try to uninstall pytorch package and install pytorch package with the command ```conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch```, the CUDA version of my nvidia gpus is 11.5, please confirm the version is higher than the cudatoolkit version of pytorch package.

**Comment by yuanze-lin** [comment]
Many thanks for your feedback, I've updated the README file, you can use ```requirements.yaml``` to install the anaconda environment. I think this can solve your problem.

**Comment by ningkekeke** [comment]
@yzleroy No more words can express my gratitude to you, I will try again carefully according to your updated file and wish you all the best. :)

**Comment by yuanze-lin** [comment]
@ningkekeke you are welcome : )
