### ISSUE TITLE
About ensemble.py

### ISSUE THREAD

**Issue by hc0527** [leroy102/REVIVE#6]
Hello dear author, can you be more specific about how to implement the use of ensemble.py to integrate the results of three predictions

**Comment by yuanze-lin** [comment]
@hc0527 Thank you for your attention.

Sure, if you train three models using three different seeds and get their predictions as json file (e.g., prediction1.json, prediction2.json and prediction3.json), then ensemble.py will get the final outputs among all predictions by considering prediction frequency for each sample, we choose the prediction with the highest prediction frequency for each test sample.

Note that using different seeds is very important. I've tried to train three models using different hyper-parameters with the same seed, and then perform ensembling, but the final performance wouldn't be improved.
