### ISSUE TITLE
您好，这是一个非常好的工作。请问，train.pkl里的’im_ctxs', 'ex_ctxs', 'boxes', 'vis_feat', 'tags'分别指代的什么呢？

### ISSUE THREAD

**Issue by qppwddd** [leroy102/REVIVE#7]

**Comment by yuanze-lin** [comment]
@qppwddd  Sorry for the confusion.

"im_ctxs": implicit knowledge, each one among it means one implicit knowledge sample. 
"ex_ctxs": explicit knowledge, each one among it means one explicit knowledge sample. 
"boxes": detected bounding boxes from the object detector.
"vis_feat": visual features which correspond to the detected bounding boxes.
"tags": retrieved tags according to CLIP similarity.

**Comment by qppwddd** [comment]
thanks,i get it
